Patched strange hidden keys getting displayed
emlun/yubikey-oath-dmenu pull request #4
Opened 2018-10-08 13:11 UTC by relatev

I don't know if this is intended, but I always got some keys displayed with an underscore in front (maybe something internal of the oath?). These didn't seem to have any functionality to me so I just patched it to hide them.

2018-10-08 13:29 UTC, emlun requested changes
Thanks for contributing! I think these credentials are used by specific integration solutions that automate the OATH step and hide it away from the user.

However, I don't think this should be the default. Would you mind adding a `--no-hidden` CLI option that enables this behaviour?

2018-10-08 13:29 UTC, emlun commented on yubikey-oath-dmenu
> +            for cred in ctrl.list() if not cred.printable_key.startswith("_")
Suggestion: `if not (no_hidden and cred.printable_key.startswith("_"))`

2018-10-08 13:54 UTC, wjrtz commented
Added it as a CLI option. Didn't know what to write about it in the help text..

By the way, this is a really useful little script you wrote here! Thanks!

2018-10-08 13:57 UTC, emlun approved these changes
Great, thanks!

2018-10-08 13:59 UTC, emlun commented
Thanks for using it, and thanks again for contributing!

2018-10-08 13:59 UTC, merged

2018-10-09 06:39 UTC, emlun commented
This is now merged and released; let me know if you'd like to be attributed by offline name!